### ISSUE TITLE
¿Módulo de localización o genérico?

### ISSUE THREAD

**Issue by grottas** [exaap/l10n-colombia#5]
@JoanMarin

https://github.com/exaap/l10n-colombia/tree/10.0/l10n_co_partner_isic

¿Este módulo debe ser de localización? o ¿podría ser genérico para el partner?

Si es genérico, iría a este repositorio:

https://github.com/OCA/partner-contact

**Comment by Capriatto** [comment]
@grottas El ISIC es un estándar internacional (en inglés CIIU). Sin embargo, no es genérico porque la DIAN expidió mediante [resolución 000139 de 2012](https://www.dian.gov.co/ciiu/Paginas/normasciiu.aspx) la adaptación para Colombia que es la utilizada en este módulo que mencionas.

**Comment by grottas** [comment]
@Capriatto Sería viable uno genérico para el partner y luego uno para adaptarlo a Colombia como localización?

**Comment by Capriatto** [comment]
si, por ahora no encuentro algún módulo genérico que lo haga.
